<!DOCTYPE html>
<html ng-app="notesApp">
	<head>
		<meta charset="UTF-8">
		<title>$http POST example</title>
		<style>
			.item {
				padding: 10px;
			}
		</style>
	</head>
	<body ng-controller="MainCtrl as mainCtrl">
		<h2>Hello Servers!</h2>
		<div ng-repeat="todo in mainCtrl.items" class="item">
			<div><span ng-bind="todo.id"></span></div>
			<div><span ng-bind="todo.titulo"></span></div>
		</div>
		
		<div>
			<form name="addForm" ng-submit="mainCtrl.adiciona()">
				<input type="number" placeholder="Id" ng-model="mainCtrl.newBook.id" required/>
				<input type="text" placeholder="Titulo" ng-model="mainCtrl.newBook.titulo" required/>
				<input type="text" placeholder="Autor" ng-model="mainCtrl.newBook.nome" required/>
				<input type="submit" value="Adicionar" ng-disabled="addForm.$invalid">
			</form>
		</div>
		
		<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js"></script>
		<script>
			angular.module('notesApp',[])
				.controller('MainCtrl',['$http', function($http){
					var self = this;
					self.items = [];
					self.newBook = {};
					
					var populaLivros = function(){
						return $http.get('api/book').then(
							function(response){
								self.items = response.data;
							}, 
							function(errResponse){
								console.error('Erro ao consultar livros...');
							});
					};
					
					populaLivros();
					
					self.adiciona = function() {
						self.newBook.autor = [];
						self.newBook.autor.push(self.newBook.nome);
						self.newBook.nome = undefined;
						$http.post('api/book', self.newBook)
							.then(populaLivros)
							.then(function(response){
								self.newBook = {};
							});
					};
				}])
				.factory('LogInterceptor',['$q', function($q){
					return {
						request: function(config){
							console.log('Request made with: ', config);
							return config;
							// Se houver um erro, não houver permissão ou ocorrer uma condição personalizada
							// return $q.reject('Not Allowed.');
						},
						requestError: function(rejection){
							console.log('Request error due to: ', rejection);
							// Continua para garantir que a próxima cadeia de promise veja um erro
							return $q.reject(rejection);
							// Ou trata o erro e retorna algum valor para dar sucesso
							// return someValue;
						},
						response: function(response){
							console.log('Response from server: ', response);
							// Retorna uma promise
							return response || $q.when(response);
						},
						responseError: function(rejection){
							console.log('Response error: ', rejection);
							// Continua para garantir que a próxima cadeia de promise veja um erro
							// Poderíamos verificar, por exemplo, o código de status de authorization
							// if(rejection.status === 403){
							//    mostra um dialogo de login
							//    retorna um valor para dizer aos controladores que foi tratado
							//}
							// Ou retorna mesmo uma rejeição para continuar a cadeia de falhas da promise
							return $q.reject(rejection);
						}
					};
				}])
				.config(['$httpProvider', function($httpProvider){
					$httpProvider.interceptors.push('LogInterceptor');
				}]);
		</script>
	</body>
</html>